FROM __IMAGE_REF__

# Copy the auth config section
COPY .oauth.yaml /home/extralit/

# Uncoment this line to remove the persistence storage warning
ENV EXTRALIT_SHOW_HUGGINGFACE_SPACE_PERSISTENT_STORAGE_WARNING=false
