cluster.name: "docker-cluster"
network.host: 0.0.0.0
path.data: "/usr/share/elasticsearch/data"
path.logs: "/usr/share/elasticsearch/logs"
discovery.type: single-node
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
cluster.routing.allocation.disk.threshold_enabled: false

logger.level: ERROR
logger.action: ERROR
logger.transport: ERROR
logger.cluster: ERROR
logger.discovery: ERROR
logger.gateway: ERROR
logger.indices: ERROR
logger.search: ERROR
logger.mapping: ERROR
logger.index_indexing_slowlog: ERROR
logger.index_search_slowlog: ERROR
logger.index_indexing_slowlog_index_warn: ERROR
logger.index_search_slowlog_index_warn: ERROR
