name: Build extralit-hf-space Image

on:
  repository_dispatch:
    types:
      - build-hf-space
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine IMAGE_TAG
        id: determine_tag
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            TAG="${{ github.event.client_payload.tag }}"
          else
            TAG="latest"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
      - name: Set variables based on release flag
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]] && [[ "${{ github.event.client_payload.is_release }}" == "true" ]]; then
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
            echo "REPO=extralit/extralit-hf-space" >> $GITHUB_ENV
            echo "EXTRALIT_SERVER_IMAGE=extralit/extralit-server" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{ secrets.AR_DOCKER_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.AR_DOCKER_PASSWORD }}" >> $GITHUB_ENV
            echo "TAG_LATEST=true" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]] && [[ "${{ github.event.client_payload.is_release }}" != "true" ]]; then
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
            echo "REPO=extralitdev/extralit-hf-space" >> $GITHUB_ENV
            echo "EXTRALIT_SERVER_IMAGE=extralitdev/extralit-server" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{ secrets.AR_DOCKER_USERNAME_DEV }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.AR_DOCKER_PASSWORD_DEV }}" >> $GITHUB_ENV
            echo "TAG_LATEST=false" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
            echo "REPO=extralit/extralit-hf-space" >> $GITHUB_ENV
            echo "EXTRALIT_SERVER_IMAGE=extralit/extralit-server" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{ secrets.AR_DOCKER_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.AR_DOCKER_PASSWORD }}" >> $GITHUB_ENV
            echo "TAG_LATEST=false" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
            echo "REPO=extralitdev/extralit-hf-space" >> $GITHUB_ENV
            echo "EXTRALIT_SERVER_IMAGE=extralitdev/extralit-server" >> $GITHUB_ENV
            echo "DOCKER_USERNAME=${{ secrets.AR_DOCKER_USERNAME_DEV }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.AR_DOCKER_PASSWORD_DEV }}" >> $GITHUB_ENV
            echo "TAG_LATEST=true" >> $GITHUB_ENV
          else
            echo "SKIP_BUILD=true" >> $GITHUB_ENV
            echo "No matching event/branch criteria. Skipping build." >> $GITHUB_ENV
          fi

      - name: Skip build (no matching criteria)
        if: env.SKIP_BUILD == 'true'
        run: exit 1

      - name: Construct Docker tags
        run: |
          TAGS="${{ env.REPO }}:${{ env.IMAGE_TAG }}"
          if [[ "${{ env.TAG_LATEST }}" == "true" ]]; then
            TAGS="$TAGS,${{ env.REPO }}:latest"
          fi
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & push extralit-hf-space Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            EXTRALIT_SERVER_IMAGE=${{ env.EXTRALIT_SERVER_IMAGE }}
            EXTRALIT_VERSION=${{ env.IMAGE_TAG }}
          tags: ${{ env.DOCKER_TAGS }}
          push: true

    # TODO: uncomment this once the step works again
      # - name: Docker Hub Description for `extralit-server`
      #   uses: peter-evans/dockerhub-description@v4
      #   if: ${{ env.PUBLISH_LATEST == 'true' }}
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ env.DOCKER_PASSWORD }}
      #     repository: $${{ env.SERVER_DOCKER_IMAGE }}
      #     readme-filepath: extralit-server/docker/server/README.md
      # TODO: uncomment this once the step works again
      # - name: Docker Hub Description for `argilla-hf-spaces`
      #   uses: peter-evans/dockerhub-description@v4
      #   if: ${{ env.PUBLISH_LATEST == 'true' }}
      #   with:
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ env.DOCKER_PASSWORD }}
      #     repository: $${{ env.HF_SPACES_DOCKER_IMAGE }}
      #     readme-filepath: extralit-server/docker/extralit-hf-space/README.md

